dependencies:
  flutter:
      sdk: flutter
        math_expressions: ^3.1.0  # ← تم تحديثه من 2.7.0

        dev_dependencies:
          flutter_test:
              sdk: flutter
                flutter_lints: ^6.0.0      # ← تم تحديثه من 3.0.2